name: ESP32_GENERIC NOBLE (noBLE)

on:
  push:
    paths:
      - '.github/workflows/build-noble.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/esp32/**'
  pull_request:
    paths:
      - 'ports/esp32/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IDF_NEWEST_VER: "v5.3"

jobs:
  build_noble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup ESP-IDF
        uses: ./.github/actions/setup_esp32
        with:
          idf_ver: ${{ env.IDF_NEWEST_VER }}
          ccache_key: esp32_build_noble

      - name: Build esp32_build_noble
        run: tools/ci.sh esp32_build_noble

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: ESP32_GENERIC-NOBLE-${{ github.sha }}
          path: ports/esp32/build-ESP32_GENERIC-NOBLE/firmware.bin
          if-no-files-found: error
          retention-days: 30
