name: ESP32_GENERIC NOBLE (noBLE)

on:
  push:
    paths:
      - ".github/workflows/build-noble.yml"
      - "tools/ci.sh"
      - "ports/esp32/**"
      - "mpy-cross/**"
  pull_request:
    paths:
      - "ports/esp32/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read the ESP-IDF version
        id: idf_ver
        run: source tools/ci.sh && echo "IDF_VER=$IDF_VER" | tee "$GITHUB_OUTPUT"

      - name: Cache ESP-IDF
        id: cache_esp_idf
        uses: actions/cache@v4
        with:
          path: ~/.espressif
          key: esp-idf-${{ steps.idf_ver.outputs.IDF_VER }}

      - name: Install ESP-IDF
        if: steps.cache_esp_idf.outputs.cache-hit != 'true'
        run: source tools/ci.sh && ci_esp32_idf_setup

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: esp32-noble

      - name: Build ESP32_GENERIC NOBLE
        run: source tools/ci.sh && ci_esp32_build_noble

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: ESP32_GENERIC-NOBLE-${{ github.sha }}
          path: ports/esp32/build-ESP32_GENERIC-NOBLE/firmware.bin
          if-no-files-found: error
          retention-days: 30
